### ISSUE TITLE
preg_replace(): Compilation failed: unmatched closing parenthesis at offset 50

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-medialibrary#2586]
This seems to be caused by #2575, this causes issues on filenames like this:
```
[2021-05] Filename.mp4
(2021-05) Filename.mp4
{2021-05} Filename.mp4
```
I don't know if these names are not valid on Windows, but on Linux almost every character is allowed.

```
ErrorException 

  preg_replace(): Compilation failed: unmatched closing parenthesis at offset 50

  at vendor/spatie/laravel-medialibrary/src/Support/FileNamer/FileNamer.php:14
     10▕     public function originalFileName(string $fileName): string
     11▕     {
     12▕         $name = pathinfo($fileName, PATHINFO_FILENAME);
     13▕ 
  ➜  14▕         return preg_replace("/{$name}\..*/", $name, $fileName);
     15▕     }
     16▕ 
     17▕     abstract public function conversionFileName(string $fileName, Conversion $conversion): string;
     18▕ 
```

**Comment by freekmurze** [comment]
@erikn69 could you take a look at this one?

**Comment by erikn69** [comment]
Ok, i gonna fix this
